### ISSUE TITLE
Encountering class cast exception with RPC Client

### ISSUE THREAD

**Issue by alexandermjames** [activej/activej#141]
Hi,

I am encountering a class cast exception when using an RPC client to communicate from an ActiveJ HTTP server to and ActiveJ RPC Server. I am doing a performance benchmark using the framework you have provided in your other examples. I was wondering if you can shed any light on how my setup might be off or if there is an underlying issue.

`
io.activej.common.exception.UnknownFormatException: Parse exception, io.activej.datastream.csp.ChannelDeserializer@36b0cd56 : bufs:1 bytes:6102
	at io.activej.datastream.csp.ChannelDeserializer.onResumed(ChannelDeserializer.java:88)
	at io.activej.datastream.AbstractStreamSupplier.resume(AbstractStreamSupplier.java:142)
	at io.activej.datastream.AbstractStreamSupplier.asyncResume(AbstractStreamSupplier.java:135)
	at io.activej.datastream.csp.ChannelDeserializer.lambda$onResumed$1(ChannelDeserializer.java:117)
	at io.activej.promise.AbstractPromise$25.accept(AbstractPromise.java:1134)
	at io.activej.promise.AbstractPromise.complete(AbstractPromise.java:114)
	at io.activej.promise.SettablePromise.set(SettablePromise.java:68)
	at io.activej.csp.queue.ChannelZeroBuffer.put(ChannelZeroBuffer.java:83)
	at io.activej.csp.queue.ChannelQueue$1.doAccept(ChannelQueue.java:66)
	at io.activej.csp.AbstractChannelConsumer.accept(AbstractChannelConsumer.java:51)
	at io.activej.csp.ChannelSuppliers.lambda$streamToImpl$6(ChannelSuppliers.java:236)
	at io.activej.promise.AbstractPromise.complete(AbstractPromise.java:114)
	at io.activej.promise.SettablePromise.set(SettablePromise.java:68)
	at io.activej.net.socket.tcp.AsyncTcpSocketNio.onReadReady(AsyncTcpSocketNio.java:374)
	at io.activej.eventloop.Eventloop.onRead(Eventloop.java:751)
	at io.activej.eventloop.Eventloop.processSelectedKeys(Eventloop.java:498)
	at io.activej.eventloop.Eventloop.run(Eventloop.java:411)
	at io.activej.service.adapter.ServiceAdapters$10.lambda$start$0(ServiceAdapters.java:282)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: com.traceql.storage.lmdb.api.GetTokenResponse cannot be cast to com.traceql.storage.lmdb.api.GetQuotaResponse
	at io.activej.promise.AbstractPromise$1.accept(AbstractPromise.java:196)
	at io.activej.promise.AbstractPromise.complete(AbstractPromise.java:114)
	at io.activej.promise.SettablePromise.set(SettablePromise.java:68)
	at io.activej.promise.SettablePromise.accept(SettablePromise.java:55)
	at io.activej.rpc.client.RpcClientConnection$JmxConnectionMonitoringResultCallback.onResult(RpcClientConnection.java:397)
	at io.activej.rpc.client.RpcClientConnection$JmxConnectionMonitoringResultCallback.accept(RpcClientConnection.java:385)
	at io.activej.rpc.client.RpcClientConnection.accept(RpcClientConnection.java:215)
	at io.activej.rpc.client.RpcClientConnection.accept(RpcClientConnection.java:49)
	at io.activej.datastream.AbstractStreamSupplier.send(AbstractStreamSupplier.java:153)
	at io.activej.datastream.csp.ChannelDeserializer.process(ChannelDeserializer.java:159)
	at io.activej.datastream.csp.ChannelDeserializer.onResumed(ChannelDeserializer.java:83)
	... 18 common frames omitted
`

I have ensured the the MessageTypes for both the RPC client and the RPC server are listed in the same order. Both the RPC server and HTTP server are using the Primary/Worker event loop architecture. Any thoughts or questions to help me provide more information?

**Comment by eduard-vasinskyi** [comment]
Hi, @alexandermjames

Сould you please construct a simple demo/snippet that demonstrates the problem? I believe that an HTTP server is not required for the demo, just a simple RPC client-server communication. I’ll be glad to help you.
 

It is possible that a class cast exception may occur if you mix up RPC server handler response types and RPC client `sendRequest()` response types.
Let’s say you have 2 operations: “Get token” and “Get quota”. Corresponding RPC message types would be:
[`GetTokenRequest`, `GetTokenResponse`] and [`GetQuotaRequest`, `GetQuotaResponse`]
If you mix up request/response types when calling `sendRequest()` you can get a class cast exception:
```java
client.<GetTokenRequest, GetQuotaResponse>sendRequest(new GetTokenRequest())
.map(response -> response.getQuota()); // class cast exception
```
The exception occurs because the server handles `GetTokenRequest` and responds with a `GetTokenResponse` (as set up in a handler). The client then receives a `GetTokenResponse` and tries to cast it to a `GetQuotaResponse` leading to a class cast exception.

If that is not the case, please provide a snippet or a demo.

**Comment by alexandermjames** [comment]
Hi @eduard-vasinskyi,

Thank you for your help on this one. I have provided a snippet while I get a demo for you. I think the snippet will provide sufficient information though. I understand very much what you are saying. I have scoured my code for any sign of what you reference and unfortunately I can't find anything. Let me know if you feel you need more information.

[snippet.txt](https://github.com/activej/activej/files/7823233/snippet.txt)

**Comment by alexandermjames** [comment]
In doing further debugging one of the things that I am recognizing is that this is only happening with the ".map" method from the Promise object. I have tried various different mapping chains and ultimately get the same result i.e. ClassCastException. It might be worth understanding that the requests as they come into the HTTP Server are chained AsyncServlets. As an example my flow looks like this LoggableServlet -> BasicAuth -> FinalServlet.  I am using version 5.0 of the framework. I have included an example of what the BasicAuth and FinalServlet looks like.

`
tokenService.getToken(getTokenRequest)
                           .map(GetTokenResponse::getToken)
                           .map(token -> token.verify(bearerToken))
                           .then($ -> {
                               httpRequest.attach("token", decoded);
                               return next.serveAsync(httpRequest);
                           });
`

`
httpRequest.loadBody()
                      .map(this::toRequestBodyDto)
                      .map(toGetQuotaRequest)
                      .then(quotaService::getQuota)
                      .map(GetQuotaResponse::getQuota)
                      .then(this::toHttpResponse)
`

**Comment by eduard-vasinskyi** [comment]
@alexandermjames 

Based on the `StorageRpcClient` code it seems like you haven’t mixed up RPC message types. But to be 100% sure can you execute your client/server apps with the following VM options?
```bash
-DDefiningClassLoader.debugOutputDir=%path to bytecode output dir%
```
Adding this VM option will put generated classes for RPC message serializer to the provided directory. If both serializer classes (for client and server) are the same, then messages have not been mixed up. Otherwise, could you please share the resulting classes?

=============================================================================================
You said that you use Primary/Worker event loop architecture for both the RPC server and HTTP server. But do you use this architecture for your RPC client? RPC client is bound to a certain Eventloop, so if you call the RPC client you need to make sure that you do it from within the same Eventloop it is bound to. ActiveJ has a special VM option `-Dchk=on` that enables additional state checks similar to Java’s assertions (see [Checks](https://github.com/activej/activej/blob/master/util-common/src/main/java/io/activej/common/Checks.java)). You can enable this option to verify that you haven’t made any logical mistakes within your code. Although note that this VM option is only for debug/development purposes as it may hurt the performance a little.

If you enable this option and then receive errors like `java.lang.IllegalStateException: Not in eventloop thread`, make sure that RPC client is created with worker eventloop instead of a primary one. You will have to provide a `RpcClient`, `StorageClient` as well as `QuotaService`/`TokenService` within `@Worker` scope.

If this is not the case, please provide a reproducible demo.

**Comment by alexandermjames** [comment]
@eduard-vasinskyi Thank you for the feedback. I will be trying these things today and will get back to you shortly. Thanks!

**Comment by alexandermjames** [comment]
@eduard-vasinskyi I was able to resolve the issue with your suggestions. Thank you for the help again!
