### ISSUE TITLE
Exception about websocket

### ISSUE THREAD

**Issue by zhangtianxiao** [activej/activej#197]
I wrote a simplify demo https://github.com/zhangtianxiao/activej-5.0-websocket-demo-java8
I can't understand why this exception will happen.
Run demo, and open index.html by chrome, press f5 multiple times.  you can reproduce this exception.
```
onConnected
received: test1
13:24:36.159 [main] ERROR io.activej.eventloop.Eventloop - Fatal error in AsyncTcpSocketImpl{channel=java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:10000 remote=/0:0:0:0:0:0:0:1:51290], readBuf=null, writeBuf=null, readEndOfStream=false, writeEndOfStream=false, read=SettablePromise
	.whenComplete(ChannelSuppliers$$Lambda$73), write=null, ops=-123}
java.lang.NullPointerException: null
	at io.activej.net.socket.tcp.AsyncTcpSocketNio.onWriteReady(AsyncTcpSocketNio.java:502)
	at io.activej.eventloop.Eventloop.onWrite(Eventloop.java:768)
	at io.activej.eventloop.Eventloop.processSelectedKeys(Eventloop.java:503)
	at io.activej.eventloop.Eventloop.run(Eventloop.java:411)
	at dem.activej.WebSocketDemo.main(WebSocketDemo.java:25)
```

Important difference is `(WebSocketDemoServlet.java:51)`,  there call writeMessage  in  a thread executor instead of in eventloop thread.
@eduard-vasinskyi

**Comment by zhangtianxiao** [comment]
`eventloop.postLast{ websocket.send() }`, that's fine
