### ISSUE TITLE
Rpc server listen with exception...

### ISSUE THREAD

**Issue by xsank** [activej/activej#236]
`
java.lang.ArrayIndexOutOfBoundsException: 0
  at org.objectweb.asm.Frame.merge(Frame.java:1268)
  at org.objectweb.asm.Frame.merge(Frame.java:1233)
  at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1610)
  at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1546)
  at org.objectweb.asm.commons.GeneratorAdapter.endMethod(GeneratorAdapter.java:1348)
  at io.activej.codegen.ClassBuilder.toBytecode(ClassBuilder.java:484)
  at io.activej.codegen.ClassBuilder.toBytecode(ClassBuilder.java:393)
  at io.activej.codegen.ClassBuilder.toBytecode(ClassBuilder.java:381)
  at io.activej.codegen.ClassBuilder.defineClass(ClassBuilder.java:355)
  at io.activej.codegen.ClassBuilder.defineClassAndCreateInstance(ClassBuilder.java:369)
  at io.activej.serializer.SerializerBuilder.build(SerializerBuilder.java:479)
  at io.activej.serializer.SerializerBuilder.build(SerializerBuilder.java:457)
  at io.activej.rpc.server.RpcServer.onListen(RpcServer.java:213)
  at io.activej.net.AbstractServer.listen(AbstractServer.java:226)
  at 
`
the exception is caused by 'encode_Object_2([BILjava/lang/Object;)I'

version: 5.4

**Comment by xsank** [comment]
v5.4.2 with the sampe problem

**Comment by eduard-vasinskyi** [comment]
Hi, @xsank

I can assume that the problem is related to your message types. All message types must be serializable using [ActiveJ Serializer](https://activej.io/serializer). This means that they must have the appropriate `@Serialize` annotations on message fields, as well as  the appropriate `@Deserialize` annotations on the message constructor. 

You can look at message types in [MemcacheRpcMessage#MESSAGE_TYPES](https://github.com/activej/activej/blob/943d56f7f516f219b1846d4be346c22e6b49e6a8/extra/cloud-memcache/src/main/java/io/activej/memcache/protocol/MemcacheRpcMessage.java#L39-L122) for a reference. Or, if you can share your message classes, I’d be happy to help you out with them.

**Comment by xsank** [comment]
hi @eduard-vasinskyi , all my message use the activej's @serialize&@Deserialize annotation. I will write a simple demo later to recur the bug.

**Comment by eduard-vasinskyi** [comment]
@xsank, thanks for the demo. 

There are some errors in your snippet, though. Eventloops are never started as well as the RPC client. 

I have updated your example to add start/stop routines. However, we recommend to use [ActiveJ Inject](https://activej.io/inject) to do the injection of dependencies. If you also use the [`service-graph`](https://activej.io/boot/servicegraph) module, it would automatically take care of services start/stop routines. You can use examples [RpcExample](https://github.com/activej/activej/blob/b5b5cb1fb22b07a27c4f6f3b940c68a4234b906b/examples/cloud/rpc/src/main/java/RpcExample.java) and [Advanced RpcExample](https://github.com/activej/activej/tree/master/examples/cloud/rpc/src/main/java/advancedrpc) as a reference.

After updating your example, it worked as intended. I got the string `“test”` printed out. I could not reproduce the exception you posted previously.

 Here is an updated version:
```java
import io.activej.common.exception.FatalErrorHandler;
import io.activej.eventloop.Eventloop;
import io.activej.promise.Promise;
import io.activej.rpc.client.RpcClient;
import io.activej.rpc.server.RpcServer;
import io.activej.serializer.SerializerBuilder;
import io.activej.serializer.annotations.Deserialize;
import io.activej.serializer.annotations.Serialize;
 
import java.net.InetSocketAddress;
import java.time.Duration;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutionException;
 
import static io.activej.rpc.client.sender.RpcStrategies.server;
 
public class ActivejTest {
 
  public static class GetUserIdByIdReq {
     private long id;
 
     public GetUserIdByIdReq(@Deserialize("id") long id) {
        this.id = id;
     }
 
     @Serialize
     public long getId() {
        return id;
     }
  }
 
  public static class GetUserIdByIdRes {
     private byte[] userId;
 
     public GetUserIdByIdRes(@Deserialize("userId") byte[] userId) {
        this.userId = userId;
     }
 
     @Serialize
     public byte[] getUserId() {
        return userId;
     }
  }
 
  public static class ActivejServer {
 
     private String ip;
     private int port;
 
     private RpcServer rpcServer;
     private Eventloop eventloop;
 
     public ActivejServer(String host) {
        this.ip = host.split(":")[0];
        this.port = Integer.parseInt(host.split(":")[1]);
        this.init();
     }
 
     public void init() {
        this.eventloop = Eventloop.create()
              .withEventloopFatalErrorHandler(FatalErrorHandler.rethrow())
              .withCurrentThread();
        this.rpcServer = RpcServer.create(eventloop)
              .withSerializerBuilder(SerializerBuilder.create())
              .withMessageTypes(
                    GetUserIdByIdReq.class, GetUserIdByIdRes.class)
              .withHandler(GetUserIdByIdReq.class, req -> Promise.of(getUserIdById(req)))
              .withListenPort(port);
 
        CompletableFuture<Void> listenPromise = eventloop.submit(() -> {
           try {
              this.rpcServer.listen();
           } catch (Exception e) {
              throw new RuntimeException(e);
           }
        });
 
        new Thread(eventloop).start();
 
        try {
           listenPromise.get();
        } catch (InterruptedException | ExecutionException e) {
           throw new RuntimeException(e);
        }
     }
 
     public GetUserIdByIdRes getUserIdById(GetUserIdByIdReq req) {
        return new GetUserIdByIdRes("test".getBytes());
     }
  }
 
  public static class ActivejClient {
     private String host;
     private String ip;
     private int port;
     private RpcClient rpcClient;
     private Eventloop eventloop;
 
     public ActivejClient(String host) {
        this.host = host;
        this.ip = host.split(":")[0];
        this.port = Integer.valueOf(host.split(":")[1]);
        this.init();
     }
 
     private void init() {
        this.eventloop = Eventloop.create()
              .withEventloopFatalErrorHandler(FatalErrorHandler.rethrow());
        this.rpcClient = RpcClient.create(eventloop)
              .withSerializerBuilder(SerializerBuilder.create())
              .withMessageTypes(
                    GetUserIdByIdReq.class, GetUserIdByIdRes.class)
              .withConnectTimeout(Duration.ofSeconds(3))
              .withStrategy(server(new InetSocketAddress(ip, port)));
        eventloop.keepAlive(true);
        new Thread(eventloop).start();
        try {
           eventloop.submit(() -> rpcClient.start()).get();
        } catch (InterruptedException | ExecutionException e) {
           throw new RuntimeException(e);
        }
     }
 
     public byte[] getUserIdById(long id) {
        try {
           return eventloop.submit(() -> rpcClient.<GetUserIdByIdReq, GetUserIdByIdRes>sendRequest(new GetUserIdByIdReq(id)))
                 .get()
                 .getUserId();
        } catch (InterruptedException | ExecutionException e) {
           throw new RuntimeException(e);
        }
     }
  }
 
  public static void main(String[] args) {
     ActivejServer server = new ActivejServer("localhost:13579");
     ActivejClient client = new ActivejClient("localhost:13579");
 
     String res = new String(client.getUserIdById(123));
     System.out.println(res);
     client.eventloop.submit(() -> client.rpcClient.stop());
     server.eventloop.submit(() -> server.rpcServer.close());
 
     client.eventloop.keepAlive(false);
  }
```
Does the problem still persist with an updated version?

If yes, could you try to execute the code below? Does it throw the same exception?
```java
public static void main(String[] args) {
  SerializerBuilder.create().build(GetUserIdByIdReq.class);
  SerializerBuilder.create().build(GetUserIdByIdRes.class);
 
  SerializerBuilder serializerBuilder = SerializerBuilder.create()
        .withSubclasses(RpcMessage.MESSAGE_TYPES, Arrays.asList(GetUserIdByIdReq.class, GetUserIdByIdRes.class));
  serializerBuilder.build(GetUserIdByIdReq.class);
  serializerBuilder.build(GetUserIdByIdRes.class);
}
```

What if you would remove the `RpcClient#withSerializerBuilder` and `RpcServer#withSerializerBuilder` calls? That way a client and a server would use a default serializer builder. Would that help?

**Comment by xsank** [comment]
@eduard-vasinskyi thank you for your reply, i have tried your modify but still with some problem.
```shell
Exception in thread "Thread-0" java.lang.RuntimeException: java.lang.IllegalArgumentException
	at com.test.db.engine.db.rookiedb.rpc.ActiveJTest$ActivejServer.lambda$init$1(ActiveJTest.java:77)
	at io.activej.eventloop.Eventloop.lambda$submit$2(Eventloop.java:1208)
	at io.activej.eventloop.Eventloop.executeTask(Eventloop.java:657)
	at io.activej.eventloop.Eventloop.executeConcurrentTasks(Eventloop.java:724)
	at io.activej.eventloop.Eventloop.run(Eventloop.java:544)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
	at org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
	at io.activej.serializer.SerializerBuilder$4.<init>(SerializerBuilder.java:824)
	at io.activej.serializer.SerializerBuilder.addMethodsAndGettersToClass(SerializerBuilder.java:824)
	at io.activej.serializer.SerializerBuilder.scanClass(SerializerBuilder.java:797)
	at io.activej.serializer.SerializerBuilder.doScan(SerializerBuilder.java:777)
	at io.activej.serializer.SerializerBuilder.scan(SerializerBuilder.java:756)
	at io.activej.serializer.SerializerBuilder.lambda$with$35(SerializerBuilder.java:228)
	at io.activej.types.scanner.TypeScannerRegistry.scan(TypeScannerRegistry.java:378)
	at io.activej.types.scanner.TypeScannerRegistry$Context.scan(TypeScannerRegistry.java:217)
	at io.activej.types.scanner.TypeScannerRegistry$Context.scan(TypeScannerRegistry.java:207)
	at io.activej.serializer.SerializerBuilder.lambda$with$35(SerializerBuilder.java:217)
	at io.activej.types.scanner.TypeScannerRegistry.scan(TypeScannerRegistry.java:378)
	at io.activej.types.scanner.TypeScannerRegistry$Context.scan(TypeScannerRegistry.java:217)
	at io.activej.serializer.SerializerBuilder.tryAddGetter(SerializerBuilder.java:1010)
	at io.activej.serializer.SerializerBuilder.scanGetters(SerializerBuilder.java:894)
	at io.activej.serializer.SerializerBuilder.scanClass(SerializerBuilder.java:796)
	at io.activej.serializer.SerializerBuilder.doScan(SerializerBuilder.java:777)
	at io.activej.serializer.SerializerBuilder.scan(SerializerBuilder.java:756)
	at io.activej.serializer.SerializerBuilder.lambda$with$35(SerializerBuilder.java:228)
	at io.activej.types.scanner.TypeScannerRegistry.scan(TypeScannerRegistry.java:378)
	at io.activej.types.scanner.TypeScannerRegistry.lambda$scanner$1(TypeScannerRegistry.java:359)
	at io.activej.serializer.SerializerBuilder.build(SerializerBuilder.java:477)
	at io.activej.serializer.SerializerBuilder.build(SerializerBuilder.java:457)
	at io.activej.rpc.server.RpcServer.onListen(RpcServer.java:213)
	at io.activej.net.AbstractServer.listen(AbstractServer.java:226)
	at com.test.db.engine.db.rookiedb.rpc.ActiveJTest$ActivejServer.lambda$init$1(ActiveJTest.java:75)
	... 5 more
```

if i remove the `RpcClient#withSerializerBuilder` and `RpcServer#withSerializerBuilder`,  the error would be the following
``` shell
java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
	at org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
	at io.activej.serializer.SerializerBuilder$4.<init>(SerializerBuilder.java:824)
	at io.activej.serializer.SerializerBuilder.addMethodsAndGettersToClass(SerializerBuilder.java:824)
	at io.activej.serializer.SerializerBuilder.scanClass(SerializerBuilder.java:797)
	at io.activej.serializer.SerializerBuilder.doScan(SerializerBuilder.java:777)
	at io.activej.serializer.SerializerBuilder.scan(SerializerBuilder.java:756)
	at io.activej.serializer.SerializerBuilder.lambda$with$35(SerializerBuilder.java:228)
	at io.activej.types.scanner.TypeScannerRegistry.scan(TypeScannerRegistry.java:378)
	at io.activej.types.scanner.TypeScannerRegistry.lambda$scanner$1(TypeScannerRegistry.java:359)
	at io.activej.serializer.SerializerBuilder.build(SerializerBuilder.java:477)
	at io.activej.serializer.SerializerBuilder.build(SerializerBuilder.java:457)
	at com.test.db.engine.db.rookiedb.rpc.ActiveJTest.test(ActiveJTest.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:154)
	at junit.framework.TestCase.runBare(TestCase.java:127)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at com.intellij.junit3.JUnit3IdeaTestRunner.doRun(JUnit3IdeaTestRunner.java:128)
	at junit.textui.TestRunner.doRun(TestRunner.java:109)
	at com.intellij.junit3.JUnit3IdeaTestRunner.startRunnerWithArgs(JUnit3IdeaTestRunner.java:49)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

**Comment by eduard-vasinskyi** [comment]
@xsank

Based on the stack trace I can assume that the problem is with the ASM library version. You get an IllegalArgumentException when trying to instantiate the `ClassVisitor` class. The constructor of `ClassVisitor` performs a check for the ASM library version and if the version is unsupported, throws an IllegalArgumentException. 

We use ASM version 9.2. You may get the exception thrown if your version of ASM is 7 or lower. Could you verify that this is the case? What if you add an explicit dependency for ASM with a more recent version to your `pom.xml`?
```xml
<dependency>
 <groupId>org.ow2.asm</groupId>
 <artifactId>asm</artifactId>
 <version>9.2</version>
</dependency>
```

**Comment by xsank** [comment]
@eduard-vasinskyi thanks again, i found a low `asm` version in kryo package
``` shell
[INFO] |  +- io.activej:activej-datastream:jar:5.4.2:compile
[INFO] |  |  +- io.activej:activej-serializer:jar:5.4.2:compile
[INFO] |  |  |  \- io.activej:activej-codegen:jar:5.4.2:compile
[INFO] |  |  |     \- org.ow2.asm:asm-commons:jar:9.2:compile
[INFO] |  |  |        +- org.ow2.asm:asm-tree:jar:9.2:compile
[INFO] |  |  |        \- org.ow2.asm:asm-analysis:jar:9.2:compile
[INFO] |  |  \- io.activej:activej-csp:jar:5.4.2:compile
[INFO] |  \- org.jetbrains:annotations:jar:22.0.0:compile
[INFO] +- io.netty:netty-all:jar:4.1.42.Final:compile
[INFO] +- com.esotericsoftware:kryo:jar:4.0.2:compile
[INFO] |  +- com.esotericsoftware:reflectasm:jar:1.11.3:compile
[INFO] |  |  \- org.ow2.asm:asm:jar:5.0.4:compile
```
after exclude the one, activej works well now! I will learn about the asm later. Thanks for your help again~
