### ISSUE TITLE
SerializeNullable annotation not work

### ISSUE THREAD

**Issue by xsank** [activej/activej#242]
protocol
```java
public class GetUserIdByIdRes {
    private @SerializeNullable byte[] userId;

    public GetUserIdByIdRes(@Deserialize("userId") byte[] userId) {
        this.userId = userId;
    }

    @Serialize
    public byte[] getUserId() {
        return userId;
    }
}
```
exception
```shell
java.util.concurrent.ExecutionException: io.activej.rpc.protocol.RpcRemoteException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
	at com.test.rookiedb.rpc.RookieClient.multiGet(RookieClient.java:150)
	at com.test.rookiedb.rpc.RookieClient.getUserIdById(RookieClient.java:168)
	at com.test.rookiedb.RookieDbEngine.getUserIdById(RookieDbEngine.java:190)
	at com.test.BaseEngine.read(BaseEngine.java:164)
	at com.test.DefaultEngine.read(DefaultEngine.java:116)
	at com.test.DefaultEngineTest$ReadTask.run(DefaultEngineTest.java:161)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.activej.rpc.protocol.RpcRemoteException: java.lang.NullPointerException
```

**Comment by xsank** [comment]
it seems that the RpcMessage is encoded by `Object_1` serializer

**Comment by xsank** [comment]
It is the document problem...  bad practice one: https://activej.io/serializer/examples
the right one is
```java
public class GetIdByUserIdRes {
    private Long id;

    public GetIdByUserIdRes(@Deserialize("id") Long id) {
        this.id = id;
    }

    @Serialize
    @SerializeNullable
    public Long getId() {
        return id;
    }
}
```

**Comment by KciNKh** [comment]
> ```java
> public class GetUserIdByIdRes {
>     private @SerializeNullable byte[] userId;
> 

Maybe you wanted
```java
public class GetUserIdByIdRes {
   @Serialize
   private byte @SerializeNullable [] userId;
```

**Comment by xsank** [comment]
but there is another bug, the nullable attribution would be serialize to empty obj not `null`
eg:
byte[] -> byte[0]

**Comment by KciNKh** [comment]
The nullable attribute does not replace empty with null. if you need to serialize null instead of a empty array, then you can use a getter in which to explicitly represent an empty array as null
```java
public class GetUserIdByIdRes {
    private byte [] userId;

    public GetUserIdByIdRes(@Deserialize("userId") byte [] userId) {
        this.userId = userId;
    }

    @Serialize
    public byte @SerializeNullable [] getUserId() {
        return userId == null || userId.length ==0 ? null : userId;
    }
}
```

**Comment by xsank** [comment]
@KciNKh ，in fact the userId is `null` not empty or with value,  but was serialized to the empty array.

**Comment by xsank** [comment]
```java
public class GetIdsBySalaryRes {
    private long[] ids;

    public GetIdsBySalaryRes(@Deserialize("ids") long[] ids) {
        this.ids = ids;
    }

    @Serialize
    @SerializeNullable
    public long[] getIds() {
        return ids;
    }
}
```
and if i add the message above the method `withMessageTypes` of `RpcClient`, will cause the exception
```shell
Exception in thread "Thread-1" java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 0
	at com.aliyun.polardbx.engine.db.rookiedb.rpc.RookieClient$ActivejClient.lambda$init$0(RookieClient.java:103)
	at io.activej.eventloop.Eventloop.lambda$submit$2(Eventloop.java:1208)
	at io.activej.eventloop.Eventloop.executeTask(Eventloop.java:657)
	at io.activej.eventloop.Eventloop.executeConcurrentTasks(Eventloop.java:724)
	at io.activej.eventloop.Eventloop.run(Eventloop.java:544)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.objectweb.asm.Frame.merge(Frame.java:1268)
	at org.objectweb.asm.Frame.merge(Frame.java:1233)
	at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1610)
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1546)
	at org.objectweb.asm.commons.GeneratorAdapter.endMethod(GeneratorAdapter.java:1348)
	at io.activej.codegen.ClassBuilder.toBytecode(ClassBuilder.java:484)
	at io.activej.codegen.ClassBuilder.toBytecode(ClassBuilder.java:393)
	at io.activej.codegen.ClassBuilder.toBytecode(ClassBuilder.java:381)
	at io.activej.codegen.ClassBuilder.defineClass(ClassBuilder.java:355)
	at io.activej.codegen.ClassBuilder.defineClassAndCreateInstance(ClassBuilder.java:369)
	at io.activej.serializer.SerializerBuilder.build(SerializerBuilder.java:479)
	at io.activej.serializer.SerializerBuilder.build(SerializerBuilder.java:457)
	at io.activej.rpc.client.RpcClient.start(RpcClient.java:294)
	at com.test.db.rookiedb.rpc.RookieClient$ActivejClient.lambda$init$0(RookieClient.java:101)
	... 5 more
```

**Comment by KciNKh** [comment]
In your original example, the location of the annotations is not correct. There are two solutions:
either without getter and with public userId
```java
public class GetUserIdByIdRes {

    @Serialize
    public byte @SerializeNullable [] userId;

    public GetUserIdByIdRes(byte [] userId) {
        this.userId = userId;
    }
}
```
in this case annotaion @Deserialize not required

or with getter with all serialize annotaions and priavte userId
```java
public class GetUserIdByIdRes {
    private byte[] userId;

    public GetUserIdByIdRes(@Deserialize("userId") byte[] userId) {
        this.userId = userId;
    }

    @Serialize
    public byte @SerializeNullable [] getUserId() {
        return userId;
    }
}
```

* and @SerializeNullable location must be before [] - read more for example [JSR308](https://www.oracle.com/technical-resources/articles/java/ma14-architect-annotations.html)

**Comment by xsank** [comment]
@KciNKh the [document](https://activej.io/serializer/examples#fixed-size-and-nullable-fields-serialization)  i read, `SerializeNullable` is in front of the `String`, i do not realize that the array is different

**Comment by xsank** [comment]
Anyway, the annotation question is over. Thanks @KciNKh , but there is another one above..

**Comment by xsank** [comment]
@KciNKh thanks for your help~
