### ISSUE TITLE
FatalErrorHandler not works under some conditions.

### ISSUE THREAD

**Issue by xsank** [activej/activej#243]
some online server maybe break down forever,  the rpc client should close in this case
```shell
08:06:00.165 [client-loop] ERROR io.activej.rpc.client.RpcClientConnection - Receiver error: /192.168.1.42:9000
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:225)
        at sun.nio.ch.IOUtil.read(IOUtil.java:199)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:393)
        at io.activej.net.socket.tcp.AsyncTcpSocketNio.doRead(AsyncTcpSocketNio.java:397)
        at io.activej.net.socket.tcp.AsyncTcpSocketNio.onReadReady(AsyncTcpSocketNio.java:364)
        at io.activej.eventloop.Eventloop.onRead(Eventloop.java:883)
        at io.activej.eventloop.Eventloop.processSelectedKeys(Eventloop.java:630)
        at io.activej.eventloop.Eventloop.run(Eventloop.java:543)
        at java.lang.Thread.run(Thread.java:855)
08:06:00.165 [client-loop] ERROR io.activej.rpc.client.RpcClientConnection - Sender error: /192.168.1.42:9000
io.activej.async.exception.AsyncCloseException: RPC Channel Closed
08:06:00.165 [client-loop] INFO io.activej.rpc.client.RpcClient - Connection closed: /192.168.1.42:9000
```
i custom a `Errorhandler` to handle this case, but found it not works, until i found the code below...

`FatalErrorHandlers`
```java
public static void handleError(@NotNull FatalErrorHandler fatalErrorHandler, @NotNull Throwable e, @Nullable Object context) {
        if (e instanceof RuntimeException || !(e instanceof Exception)) {
            fatalErrorHandler.handle(e, context);
        }

    }
```

for the `IOException` is instance of Exception and is not `RuntimeException`...

why the activej add this condition? and how should i handle the reset event immediately? thank you~

**Comment by eduard-vasinskyi** [comment]
Hi, @xsank

`FatalErrorHandler` is designed exclusively to handle runtime bugs  (like NPEs, illegal argument / state exceptions etc.). IOException received on connection drop is an expected exception, not a bug. An RPC client will try to automatically reconnect to the server. 

If you want a client to stop when a server is disconnected, you can analyze the exception received when calling the `RpcClient#sendRequest` method. Then you call the `RpcClient#stop` method:
```java
rpcClient.sendRequest(request)
             .whenException(e -> rpcClient.stop())
```
