### ISSUE TITLE
ArrayIndexOutOfBoundsException serializing static inner class

### ISSUE THREAD

**Issue by CarlSayres** [activej/activej#245]
I tried using static inner class as the request/response objects for RPC. I get the following exception:

```
Exception in thread "eventloop: pool-2-thread-1" java.lang.ArrayIndexOutOfBoundsException: 2
	at io.activej.serializer.SerializerBuilder.scanConstructors(SerializerBuilder.java:959)
	at io.activej.serializer.SerializerBuilder.scanClass(SerializerBuilder.java:802)
	at io.activej.serializer.SerializerBuilder.doScan(SerializerBuilder.java:779)
	at io.activej.serializer.SerializerBuilder.scan(SerializerBuilder.java:758)
	at io.activej.serializer.SerializerBuilder.lambda$with$35(SerializerBuilder.java:230)
	at io.activej.types.scanner.TypeScannerRegistry.scan(TypeScannerRegistry.java:378)
	at io.activej.types.scanner.TypeScannerRegistry$Context.scan(TypeScannerRegistry.java:217)
	at io.activej.types.scanner.TypeScannerRegistry$Context.scan(TypeScannerRegistry.java:207)
	at io.activej.serializer.SerializerBuilder.lambda$with$35(SerializerBuilder.java:219)
	at io.activej.types.scanner.TypeScannerRegistry.scan(TypeScannerRegistry.java:378)
	at io.activej.types.scanner.TypeScannerRegistry$Context.scan(TypeScannerRegistry.java:217)
	at io.activej.serializer.SerializerBuilder.tryAddGetter(SerializerBuilder.java:1012)
	at io.activej.serializer.SerializerBuilder.scanGetters(SerializerBuilder.java:896)
	at io.activej.serializer.SerializerBuilder.scanClass(SerializerBuilder.java:798)
	at io.activej.serializer.SerializerBuilder.doScan(SerializerBuilder.java:779)
	at io.activej.serializer.SerializerBuilder.scan(SerializerBuilder.java:758)
	at io.activej.serializer.SerializerBuilder.lambda$with$35(SerializerBuilder.java:230)
	at io.activej.types.scanner.TypeScannerRegistry.scan(TypeScannerRegistry.java:378)
	at io.activej.types.scanner.TypeScannerRegistry.lambda$scanner$1(TypeScannerRegistry.java:359)
	at io.activej.serializer.SerializerBuilder.build(SerializerBuilder.java:479)
	at io.activej.serializer.SerializerBuilder.build(SerializerBuilder.java:459)
	at io.activej.rpc.server.RpcServer.onListen(RpcServer.java:213)
	at io.activej.net.AbstractServer.listen(AbstractServer.java:226)
	at io.activej.service.adapter.ServiceAdapters$9.lambda$start$0(ServiceAdapters.java:254)
	at io.activej.eventloop.Eventloop.executeTask$$$capture(Eventloop.java:657)
	at io.activej.eventloop.Eventloop.executeTask(Eventloop.java)
	at io.activej.eventloop.Eventloop.executeConcurrentTasks(Eventloop.java:724)
	at io.activej.eventloop.Eventloop.run(Eventloop.java:544)
	at io.activej.service.adapter.ServiceAdapters$10.lambda$start$0(ServiceAdapters.java:282)
```

This is caused by the scanConstructors method assuming that the length of the constructors parameters list will match number of parameter annotations. For an ordinary POJO this is correct. But in the case of a static inner class, the compiler re-writes the constructor to include a reference the outer class as a parameter. Thus the ArrayIndexOutOfBoundsException.

```
	private void scanConstructors(Context<SerializerDef> ctx, SerializerDefClass serializer) {
		boolean found = false;
		for (Constructor<?> constructor : ctx.getRawType().getDeclaredConstructors()) {
			List<String> fields = new ArrayList<>(constructor.getParameterTypes().length);
			for (int i = 0; i < constructor.getParameterTypes().length; i++) {
				Deserialize annotation = getAnnotation(Deserialize.class, constructor.getParameterAnnotations()[i]);
				if (annotation != null) {
					String field = annotation.value();
					fields.add(field);
				}
			}
```
This is using activej-rpc 5.4.3 and Java 8

**Comment by eduard-vasinskyi** [comment]
Hi, @CarlSayres

I assume that you tried to serialize an inner class (nested non-static class). Actually, serialization of inner classes is not supported. In order to serialize an inner class you would also need to serialize an enclosing class. ActiveJ Serializer does not support this scenario. If you need to serialize a nested class, maybe consider making the class static?

We have added a precondition for whether the serialized class is an inner class. This will be part of an ActiveJ v5.5  release.

**Comment by CarlSayres** [comment]
Hi @eduard-vasinskyi 

You're correct. One of my inner classes was not static. Thanks so much!
