### ISSUE TITLE
Specializer doesn't work correct for the expression on JDK1.8, it throw Bad local variable type exception

### ISSUE THREAD

**Issue by michaelmao999** [activej/activej#256]
I try to use ActiveJ Specializer optimize an expression engine liked your example, but the exception was thrown.

[testCase2.zip](https://github.com/activej/activej/files/10136884/testCase2.zip)

java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    com/zov/test/SpecializedClass_1.SimpleExpression$eval(Ljava/lang/Object;)Ljava/lang/Object; @61: aload
  Reason:
    Type top (current frame, locals[5]) is not assignable to reference type
  Current Frame:
    bci: @61
    flags: { }
    locals: { 'java/lang/Object', null }
    stack: { 'com/zov/test/SimpleExpression', null }
  Bytecode:
    0x0000000: 014c 2bc1 0021 9900 33b2 0024 2bc0 0021
    0x0000010: 4dc0 0018 2cb6 0028 c000 2ab6 002e 9900
    0x0000020: 1bb2 0016 2bc0 0021 4e57 2db8 0032 3a04
    0x0000030: 1904 c600 0719 043a 05b2 0016 0119 053a
    0x0000040: 063a 0757 1907 1906 b800 36b0          
  Stackmap Table:
    append_frame(@57,Null)

	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at io.activej.specializer.Specializer$Specialization.ensureInstance(Specializer.java:161)
	at io.activej.specializer.Specializer.specialize(Specializer.java:804)
	at com.zov.test.SpecializeTestCase.testSpecialize(SpecializeTestCase.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

**Comment by eduard-vasinskyi** [comment]
Hi, @michaelmao999

We have fixed the issue in a `master` branch.

The fix will be part of an ActiveJ v5.5 release. Once again, you can install ActiveJ locally from the `master` branch (by running `sh ./install.sh` from project root). After that you can use the 'ActiveJ ver. 5.5-SNAPSHOT' as a local dependency.
