### ISSUE TITLE
Specializer doesn't work correct for the expression on JDK1.8, it cause java.lang.IllegalAccessError thrown.

### ISSUE THREAD

**Issue by michaelmao999** [activej/activej#257]
After getting master branch , I retry to use ActiveJ Specializer optimize an expression engine, when the test case was perofmed,  one static variable is not accessible, so that it throw IllegalAccessError exception.

**Comment by michaelmao999** [comment]
java.lang.IllegalAccessError: tried to access field com.zov.test.SimpleExpression.mathContext from class com.zov.test.SpecializedClass_1

	at com.zov.test.SpecializedClass_1.SimpleExpression$multiply(Unknown Source)
	at com.zov.test.SpecializedClass_1.SimpleExpression$eval(Unknown Source)
	at com.zov.test.SpecializedClass_1.eval(Unknown Source)
	at com.zov.test.SpecializeTestCase.testSpecialize(SpecializeTestCase.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

**Comment by michaelmao999** [comment]
[testCase3.zip](https://github.com/activej/activej/files/10142078/testCase3.zip)

**Comment by eduard-vasinskyi** [comment]
Hi, @michaelmao999 
We have fixed this issue in the `master` branch

**Comment by michaelmao999** [comment]
thank your quick fix, the good news is that it can work now. The bad news is that it cannot help us to improve the performance with real business case.
