### ISSUE TITLE
BUG :java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 248 out of bounds for byte[234]

### ISSUE THREAD

**Issue by PanagiotisDrakatos** [activej/activej#268]
@eduard-vasinskyi Hello and sorry for bothering you again. i believe a found a bug in your library let me further explain. To begin with, i am using a lot of future of activej libraries like .net components and activej serializer because it's an awesome library. I am having a simple unit test code to reproduce the error. Here is this link. [Test_Code](https://github.com/Adrestus-net/Adrestus/blob/master/adrestus-protocol/src/test/java/io/Adrestus/protocol/TransactionChannelTest.java)

The problem is that when i sent a large portion of objects in my case transactions and specifically 5000 transactions some of them 2-3 or more are not serialized correctly after being passed to the server via socket net library and throwing this exception but the rest working properly. 

```
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 248 out of bounds for byte[234]
	at java.base/java.lang.System.arraycopy(Native Method)
	at io.activej.serializer.BinaryInput.read(BinaryInput.java:68)
	at io.activej.serializer.BinaryInput.read(BinaryInput.java:64)
	at io.Adrestus.crypto.elliptic.mapper.SignatureDataSerializer$1.decode(SignatureDataSerializer.java:37)
	at io.Adrestus.crypto.elliptic.mapper.SignatureDataSerializer$1.decode(SignatureDataSerializer.java:12)
	at io.activej.codegen.java.lang.Object_1.decode_RegularTransaction_V0(Unknown Source)
	at io.activej.codegen.java.lang.Object_1.decode(Unknown Source)
	at io.Adrestus.util.SerializationUtil.decode(SerializationUtil.java:187)
	at io.Adrestus.protocol.TransactionChannelTest.lambda$setup$0(TransactionChannelTest.java:69)
	at io.Adrestus.network.TransactionChannelHandler.lambda$BindServerAndReceive$0(TransactionChannelHandler.java:57)
	at io.activej.promise.AbstractPromise$26.accept(AbstractPromise.java:1173)
	at io.activej.promise.AbstractPromise.complete(AbstractPromise.java:114)
	at io.activej.promise.AbstractPromise$7.accept(AbstractPromise.java:427)
	at io.activej.promise.AbstractPromise.complete(AbstractPromise.java:114)
	at io.activej.promise.AbstractPromise.complete(AbstractPromise.java:103)
	at io.activej.promise.CompletePromise.run(CompletePromise.java:436)
	at io.activej.promise.AbstractPromise$11.accept(AbstractPromise.java:573)
	at io.activej.promise.AbstractPromise.complete(AbstractPromise.java:114)
	at io.activej.promise.AbstractPromise$29.accept(AbstractPromise.java:1285)
	at io.activej.promise.AbstractPromise.complete(AbstractPromise.java:114)
	at io.activej.promise.AbstractPromise$1.accept(AbstractPromise.java:202)
	at io.activej.promise.AbstractPromise.complete(AbstractPromise.java:114)
	at io.activej.promise.SettablePromise.set(SettablePromise.java:68)
	at io.activej.csp.queue.ChannelZeroBuffer.put(ChannelZeroBuffer.java:83)
	at io.activej.csp.queue.ChannelQueue$1.doAccept(ChannelQueue.java:66)
	at io.activej.csp.AbstractChannelConsumer.accept(AbstractChannelConsumer.java:51)
	at io.activej.csp.ChannelSuppliers.lambda$streamToImpl$6(ChannelSuppliers.java:236)
	at io.activej.promise.AbstractPromise.complete(AbstractPromise.java:114)
	at io.activej.promise.SettablePromise.set(SettablePromise.java:68)
	at io.activej.net.socket.tcp.AsyncTcpSocketNio.onReadReady(AsyncTcpSocketNio.java:374)
	at io.activej.eventloop.Eventloop.onRead(Eventloop.java:883)
	at io.activej.eventloop.Eventloop.processSelectedKeys(Eventloop.java:630)
	at io.activej.eventloop.Eventloop.run(Eventloop.java:543)
```
Why is this happening is it a problem from my side or its a library problem could you please take a quick look?

To help you i notice that the problem occurred when i custom serialize the signatureDataserializer class of the transaction object and the exception was caught in this line of code

https://github.com/Adrestus-net/Adrestus/blob/70eb2527ec191d9b176803cdbd7df45b97775318/adrestus-crypto/src/main/java/io/Adrestus/crypto/elliptic/mapper/SignatureDataSerializer.java#L37

I would be glad if you run my unit test that i provide and observe this weird error that occurred

**Comment by eduard-vasinskyi** [comment]
Hi, @PanagiotisDrakatos

The problem seems to be with chosen message encoding. You use `ByteBufsDecoder#ofCrlfTerminatedBytes` to decode messages. It expects messages to end with `\r\n`. However, your data may also contain `\r\n`, so deserializer does not decode the full message but rather part of it. You can verify that this is the case by modifying the `loadData(Transaction)` method:
```java
private static @NotNull Promise<ByteBuf> loadData(Transaction transaction) {
    byte transaction_hash[] = encode.encode(transaction, 1024);
    for (int i = 0; i < transaction_hash.length - 1; i++) {
        if (transaction_hash[i] == '\r' && transaction_hash[i+1] == '\n'){
            throw new RuntimeException("CR LF conflict");
        }
    ByteBuf appendedBuf = ByteBufPool.append(ByteBuf.wrapForReading(transaction_hash), ByteBuf.wrapForReading("\r\n".getBytes()));
    return Promise.of(appendedBuf);
}
```


You could try to somehow escape the `\r\n` sequence in your data. Alternatively, you could use a different `ByteBufsDecoder`. One option is to use size-prefixed message encoding. For example, you could use `ByteBufsDecoder.ofVarIntSizePrefixedBytes()` as your `DECODER`. And then encode your message in `loadData(Transaction)` like this:
```java
private static @NotNull Promise<ByteBuf> loadData(Transaction transaction) {
    byte transaction_hash[] = encode.encode(transaction, 1024);
    ByteBuf sizeBuf = ByteBufPool.allocate(2); // enough to serialize size 1024
    sizeBuf.writeVarInt(transaction_hash.length);
    ByteBuf appendedBuf = ByteBufPool.append(sizeBuf, ByteBuf.wrapForReading(transaction_hash));
    return Promise.of(appendedBuf);
}

**Comment by PanagiotisDrakatos** [comment]
@eduard-vasinskyi Brilliant!!!!!!!!!!! working like charm. Solved
