### ISSUE TITLE
Serializer sometimes decodes a wrong class for RPC request

### ISSUE THREAD

**Issue by ocervinka** [activej/activej#282]
Those are not very good steps to reproduce as the application code currently lives in two places, a Kafka Streams IQ library and a service which uses the library.

1. In one application both RPC client and server are created with the SAME message types (`Request` and `Response`).
2. When the client sends `Request` to the same application (the application call itself), the server always decodes it as `Request`, looks up a request handler and responds with `Response`.
3. When the client sends `Request` to a different instance of an application the application either behaves as described in 2 or the server receives `Response` and fails because as expected it founds not request handler for `Response` class.
4. After an application starts it either always behaves as 2 or always as 3. Obviously this behaviour determined at application start up time. It might be a byte-code generation issue. Note that the service is written in Micronaut. It only uses the Kafka Streams IQ library as a middle-ware which starts ActiveJ event loop and does RPC calls.

The Kafka Streams IQ library pulls ActiveJ 5.4.3 as dependency.
The service uses the Kafka Streams IQ library and Micronaut 3.7.3

When I debug the service I can trace the issue as far as `ChannelDeserializer#process` where it calls `BinarySerializer#decode`
```
T item = valueSerializer.decode(array, pos + headerSize);
```

I can't step in further as the `valueSerializer` is byte-code generated. On some application instances the returned `item` is `Request` (correct) but on other instances it is `Response` (incorrect). The length of `array` and at least the beginning of the `array` is the same for both cases so I believe those are correct bytes for `Request`. The `decode` method does not fail it just returns a wrong type of object.

Note that Micronaut also uses byte-code generation.

I seek advice at this stage just in case there is already enough clues. Otherwise, I can try to rip the code from the library and the service and an example code which reproduces the issue. Maybe I can also try exactly the same use-case but outside of Micronaut if you suggest Micronaut can cause this.

**Comment by ocervinka** [comment]
The simplest alternation of the code was to remove custom serializers and simplify `Request` and `Response` records. I also made them exactly the same.
```
public record Request (
        @Deserialize("label") String label
) {
    @Override
    @Serialize(order = 1)
    public String label() {
        return label;
    }
}
```
and
```
public record Response (
        @Deserialize("label") String label
) {
    @Override
    @Serialize(order = 1)
    public String label() {
        return label;
    }
}
```
those are now the only message types registered along with a single request handler. 

RPC client sends `Request`. RPC server decodes `Response` (not expected) with the data being correct (`label=testLabel`) and then can't look up the handler (expected).

```
2023-04-28T10:28:38.869Z INFO io.activej.rpc.server.RpcServer [RPC Event Loop] Client connected on RpcServerConnection{address=/127.0.0.1, active=1, successes=0, failures=0}

2023-04-28T10:28:38.878Z WARN  hostName i.a.rpc.server.RpcServerConnection [RPC Event Loop] Exception while processing request ID 1
io.activej.common.exception.MalformedDataException: Failed to process request Response[label=testLabel]
	at io.activej.rpc.server.RpcServerConnection.serve(RpcServerConnection.java:72)
	at io.activej.rpc.server.RpcServerConnection.accept(RpcServerConnection.java:85)
	at io.activej.rpc.server.RpcServerConnection.accept(RpcServerConnection.java:39)
	at io.activej.datastream.AbstractStreamSupplier.send(AbstractStreamSupplier.java:153)
	at io.activej.datastream.csp.ChannelDeserializer.process(ChannelDeserializer.java:159)
	at io.activej.datastream.csp.ChannelDeserializer.onResumed(ChannelDeserializer.java:83)
	at io.activej.datastream.AbstractStreamSupplier.resume(AbstractStreamSupplier.java:142)
	at io.activej.datastream.AbstractStreamSupplier.asyncResume(AbstractStreamSupplier.java:135)
	at io.activej.datastream.csp.ChannelDeserializer.lambda$onResumed$1(ChannelDeserializer.java:117)
	at io.activej.promise.AbstractPromise$25.accept(AbstractPromise.java:1134)
	at io.activej.promise.AbstractPromise.complete(AbstractPromise.java:114)
	at io.activej.promise.SettablePromise.set(SettablePromise.java:68)
	at io.activej.csp.queue.ChannelZeroBuffer.put(ChannelZeroBuffer.java:83)
	at io.activej.csp.queue.ChannelQueue$1.doAccept(ChannelQueue.java:66)
	at io.activej.csp.AbstractChannelConsumer.accept(AbstractChannelConsumer.java:51)
	at io.activej.csp.ChannelSuppliers.lambda$streamToImpl$6(ChannelSuppliers.java:236)
	at io.activej.promise.AbstractPromise.complete(AbstractPromise.java:114)
	at io.activej.promise.SettablePromise.set(SettablePromise.java:68)
	at io.activej.net.socket.tcp.AsyncTcpSocketNio.onReadReady(AsyncTcpSocketNio.java:374)
	at io.activej.eventloop.Eventloop.onRead(Eventloop.java:883)
	at io.activej.eventloop.Eventloop.processSelectedKeys(Eventloop.java:630)
	at io.activej.eventloop.Eventloop.run(Eventloop.java:543)
```

**Comment by eduard-vasinskyi** [comment]
Hi, @ocervinka

You said that the same message types are used on client and server. But is the order of message types the same? If not, then this could cause the issue.

If you are sure that the order of message types is the same on the client and on the server, then could you please create a minimalistic demo that demonstrates the problem? Then I will try to help you with the issue.

**Comment by ocervinka** [comment]
@eduard-vasinskyi thanks for your help. Indeed the order of message types in `List` argument of `RpcServer#withMessageTypes` method wasn't guaranteed.

I suggest mentioning in Javadoc of that method that the order is important and must be the same for all application instances in order to communicate to each other.

When `RpcServer` and `RpcClient` are used directly there is less chance of making this mistake. However, the library kept message types in a `Set` for uniqueness because multiple subjects can register their KS IQ calls independently. Then it converted the `Set` to a `List` which caused the random deserialisation failures.

**Comment by eduard-vasinskyi** [comment]
@ocervinka
We will mention in Javadoc that the order of message types matters.

**Comment by ocervinka** [comment]
@eduard-vasinskyi do you want me to close the issue?

I can create PR with the Javadoc update, although the `RpcServer#withMessageTypes` is not in master anymore. It's been replaced by `RpcServer#withSerializer` so the Javadoc should be probably added to `RpcMessageSerializer#of`methods?

**Comment by eduard-vasinskyi** [comment]
@ocervinka
I have updated javadocs in the `master-5.5` branch. These changes have been merged into the `master` branch.
