### ISSUE TITLE
Happen error with Serializer in native app

### ISSUE THREAD

**Issue by anboo44** [activej/activej#299]
I make a small code to test native-image by using GraalVm:

<img width="642" alt="Screen Shot 2023-11-15 at 16 44 34" src="https://github.com/activej/activej/assets/19175021/d882b840-7b6a-4d0c-a797-077b195bf948">

After build successfully, I run the app and error happens

`
Exception in thread "main" java.lang.IllegalArgumentException: Parent constructor not found: Object with arguments ()
	at io.activej.codegen.Context.invokeSuperConstructor(Context.java:438)
	at io.activej.codegen.expression.impl.SuperConstructor.load(SuperConstructor.java:39)
	at io.activej.codegen.ClassGenerator.generateBytecode(ClassGenerator.java:432)
	at io.activej.codegen.ClassGenerator.generateBytecode(ClassGenerator.java:398)
	at io.activej.codegen.ClassGenerator.generateClass(ClassGenerator.java:371)
	at io.activej.codegen.ClassGenerator.generateClassAndCreateInstance(ClassGenerator.java:386)
	at io.activej.serializer.SerializerFactory.create(SerializerFactory.java:461)
	at io.activej.serializer.SerializerFactory.create(SerializerFactory.java:465)
	at com.uet.microservices.Test.main(Test.java:7)
`

It is OK when run jar file.

**Comment by eduard-vasinskyi** [comment]
Hi, @anboo44

You have to properly set up the `native-image` tool by specifying all reflection access points. You also need to configure your `Modal` class to be accessible as a resource. Since ActiveJ generates new classes you also need to specify a configuration for predefined classes. 

This configuration goes out of the scope of the ActiveJ project and is more of a GraalVM/native-image issue. 
I was able to run your example by creating a fat jar and then running a native-image agent with [`experimental-class-define-support`](https://www.graalvm.org/latest/reference-manual/native-image/metadata/ExperimentalAgentOptions/) option on it and then using generated configuration files to generate a binary executable.

This works for known classes but unfortunately would not work if your application generates new classes dynamically, since `native-image` only supports generating predefined classes.

**Comment by anboo44** [comment]
@eduard-vasinskyi You mean it is impossible to build native-image in this case, don't you ?

**Comment by anboo44** [comment]
@eduard-vasinskyi Thank you so much. It worked
I note my steps if anyone needs: 
- Build jar file
- Run command: `java -agentlib:native-image-agent=config-output-dir=config,experimental-class-define-support -jar file_name.jar` => it will create new folder with name: `config`
- In `resources`, create new folder with name: `META-IF` and then copy above `config` folder to `META-IF`. After that, rename `config` to `native-image`
- Build jar file again
- Run command: `native-image -jar file_name.jar` 
=> DONE
