### ISSUE TITLE
Current DNS Client is Incompatible with Kubernetes Deployment

### ISSUE THREAD

**Issue by zzl221000** [activej/activej#315]
The primary issue is that the default DNS server is not the system's DNS server but rather an internally defined Google DNS server. 
```java
private InetSocketAddress dnsServerAddress = GOOGLE_PUBLIC_DNS;
```

Additionally, Kubernetes automatically updates the `resolve.conf` file with cluster-related search parameters, which is essential for services within the Kubernetes environment to communicate with each other via domain names as specified in RFC 3397.

**Comment by eduard-vasinskyi** [comment]
Hi, @zzl221000 
You can create `HttpClient` with a custom `DnsClient` that uses a preferred DNS server address. 
Here is an example:
```java
InetAddress dnsServerAddress = InetAddress.getByName("my.dns.server");

IDnsClient dnsClient = DnsClient.builder(reactor)
   .withDnsServerAddress(dnsServerAddress)
   .build();


HttpClient httpClient = HttpClient.builder(reactor)
   .withDnsClient(dnsClient)
   .build();
```

**Comment by zzl221000** [comment]
Hi @eduard-vasinskyi  , I certainly know that it is possible to create a dnsclient, but the current dnsclient does not support the search parameter.
Now I have to enter the full domain address
`{servicename}.{namespace}.svc.cluster.local`

**Comment by zzl221000** [comment]
@eduard-vasinskyi 
After several days of investigation, I found that the current DNS client has no issues. The problem lies in the `httpclient` holding onto the DNS client when it should be using a DNS resolver. The DNS resolver needs to handle hostname requests, hosts file resolution, and manage the DNS client for domain name resolution.

**Comment by eduard-vasinskyi** [comment]
@eduard-vasinskyi
Could you provide a step-by-step instruction on how to reproduce the issue?

**Comment by zzl221000** [comment]
## fisrt case config domain in hosts file 
1. edit system hosts file

add content
```hosts
127.0.0.1 postgres
```
2. copy `examples/core/http/src/main/java/HttpClientExample.java`

change `http://127.0.0.1:8080/` to `http://postgres:8080/`
run then get exception
```
Exception in thread "main" java.util.concurrent.ExecutionException: io.activej.http.HttpException: io.activej.dns.protocol.DnsQueryException: DnsQuery{domainName='postgres', recordType=A} failed with error code: NAME_ERROR
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at com.winhc.data.http.HttpClientExample.run(HttpClientExample.java:88)
	at io.activej.launcher.Launcher.launch(Launcher.java:169)
	at com.winhc.data.http.HttpClientExample.main(HttpClientExample.java:95)
Caused by: io.activej.http.HttpException: io.activej.dns.protocol.DnsQueryException: DnsQuery{domainName='postgres', recordType=A} failed with error code: NAME_ERROR
Caused by: io.activej.dns.protocol.DnsQueryException: DnsQuery{domainName='postgres', recordType=A} failed with error code: NAME_ERROR
```
 ## second case config search domains 
 ```conf
search example.com local.test
nameserver 10.0.0.17
nameserver 10.1.0.12
nameserver 10.16.0.7
```
The default dnsclient implementation provided by ActiveJ does not support adding search domain parameters. The DNS resolution in Vert.x handles this aspect. Domain name resolution is not only sourced from DNS servers; clients also have relevant configurations.
Lastly, I believe that both the DNS client and HTTP client in ActiveJ are quite robust. However, the way the HTTP client uses domain names is restricted to resolution via DNS servers. Perhaps we should make some modifications, similar to how Vert.x handles it using [Vert.x DnsResolver](https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/dns/impl/DnsAddressResolverProvider.java). 
While I can implement the `IDnsClient` interface directly to achieve the functionality of a standard DNS resolver, it still feels somewhat awkward.
@eduard-vasinskyi

**Comment by Raxmatillo-Maribjonov** [comment]
Hi @zzl221000 

I also came across to this issue, how did you solve this?

**Comment by zzl221000** [comment]
> Hi [@zzl221000](https://github.com/zzl221000)
> 
> I also came across to this issue, how did you solve this?

I set the dns server to the internal dns address of k8s, which temporarily solved this problem.
