### ISSUE TITLE
Java 21 is not supported

### ISSUE THREAD

**Issue by l16h7n1n6s** [activej/activej#325]
Hello,

When I try to use Java 21 JDK with maven clean install, the ActiveJ library generates the following error. Could you make it compatible with Java 21, or is this not possible? Alternatively, is there any other solution to bypass this error?

Thank you for your assistance.
```
java.lang.IllegalArgumentException: Unsupported class file major version 65
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:287)
	at io.activej.serializer.SerializerFactory.resolveMembersOrder(SerializerFactory.java:903)
	at io.activej.serializer.SerializerFactory.scanClass(SerializerFactory.java:735)
	at io.activej.serializer.SerializerFactory.doScan(SerializerFactory.java:715)
	at io.activej.serializer.SerializerFactory.scan(SerializerFactory.java:686)
	at io.activej.serializer.SerializerFactory$Builder.lambda$with$0(SerializerFactory.java:227)
	at io.activej.types.scanner.TypeScannerRegistry.scan(TypeScannerRegistry.java:377)
	at io.activej.types.scanner.TypeScannerRegistry$Context.scan(TypeScannerRegistry.java:217)
	at io.activej.serializer.SerializerFactory.scanGetters(SerializerFactory.java:800)
	at io.activej.serializer.SerializerFactory.scanClass(SerializerFactory.java:733)
	at io.activej.serializer.SerializerFactory.scanClass(SerializerFactory.java:728)
	at io.activej.serializer.SerializerFactory.doScan(SerializerFactory.java:715)
	at io.activej.serializer.SerializerFactory.scan(SerializerFactory.java:686)
	at io.activej.serializer.SerializerFactory$Builder.lambda$with$0(SerializerFactory.java:227)
	at io.activej.types.scanner.TypeScannerRegistry.scan(TypeScannerRegistry.java:377)
	at io.activej.types.scanner.TypeScannerRegistry.lambda$scanner$1(TypeScannerRegistry.java:358)
	at io.activej.serializer.SerializerFactory.toSerializerDef(SerializerFactory.java:475)
	at io.activej.serializer.SerializerFactory.toSerializerDef(SerializerFactory.java:419)
	at io.activej.serializer.SerializerFactory.toClassGenerator(SerializerFactory.java:415)
	at io.activej.serializer.SerializerFactory.create(SerializerFactory.java:402)
	at io.activej.serializer.SerializerFactory.create(SerializerFactory.java:406)
```

**Comment by eduard-vasinskyi** [comment]
Hi, @l16h7n1n6s 

We have not faced any issues on Java 21. 

Does an error occur when you are calling `mvn clean install` on the ActiveJ project or some external project that has ActiveJ as a dependency? If it’s the latter, could you share a simple project with steps to reproduce the problem?

Which versions of ActiveJ, Maven, and the JDK (vendor included) are you using?

**Comment by eduard-vasinskyi** [comment]
@l16h7n1n6s 

I think I figured out what the problem is
The problem is with the ASM version. When checking the version of a class file, an older version of ASM doesn't know about java version 21 and throws an error.
You can solve the problem in two ways:
- build activej from the master branch and use this local version (6.0-SNAPSHOT) in your project
- specify a dependency on asm (and asm-commons) in your project with the minimum version required for java 21 (ASM version 9.5 minimum):
```xml
    <dependency>
      <groupId>org.ow2.asm</groupId>
      <artifactId>asm</artifactId>
      <version>9.5</version>
    </dependency>
    <dependency>
      <groupId>org.ow2.asm</groupId>
      <artifactId>asm-commons</artifactId>
      <version>9.5</version>
    </dependency>
```

The second option seems simpler to me.

**Comment by l16h7n1n6s** [comment]
@eduard-vasinskyi
That's incredible i can't believe it your read my mind, I was trying to post the same solution. For me the problem was at serialization/deserialization phase and I figure  out the same thing with the asm. thnxxx problem solved you can close it the issue!

```
<dependency>
    <groupId>org.ow2.asm</groupId>
    <artifactId>asm</artifactId>
    <version>9.7.1</version>
</dependency>
```
