### ISSUE TITLE
Tutorial on writing a serializer?

### ISSUE THREAD

**Issue by gkopff** [activej/activej#57]
Do you have a tutorial on writing a serializer?

**Comment by gkopff** [comment]
A naive approach to writing a serializer for a `LocalDate` was:

```
public class SerializerDefLocalDate extends AbstractSerializerDef implements SerializerDef
{
  /**
   * Returns the raw type of object which will be serialized
   * @return type of object which will be serialized
   */
  @Override
  public Class<?> getEncodeType()
  {
    return LocalDate.class;
  }

  @Override
  public Expression encoder(final StaticEncoders staticEncoders,
                            final Expression buf,
                            final Variable pos,
                            final Expression value,
                            final int version,
                            final CompatibilityLevel compatibilityLevel)
  {
    return sequence(
        writeVarInt(buf, pos, call(value, "getYear")),
        writeVarInt(buf, pos, call(value, "getMonthValue")),
        writeVarInt(buf, pos, call(value, "getDayOfMonth")));
  }

  @Override
  public Expression decoder(final StaticDecoders staticDecoders,
                            final Expression in,
                            final int version,
                            final CompatibilityLevel compatibilityLevel)
  {
    return sequence(
        readVarInt(in),
        readVarInt(in),
        readVarInt(in));
  }
}
```

however, this fails during the encoding step with:

```
Exception in thread "main" java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    io/activej/codegen/io/activej/serializer/BinarySerializer_1.decode(Lio/activej/serializer/BinaryInput;)Ljava/lang/Object; @22: checkcast
  Reason:
    Type integer (current frame, stack[2]) is not assignable to 'java/lang/Object'
  Current Frame:
    bci: @22
    flags: { }
    locals: { 'io/activej/codegen/io/activej/serializer/BinarySerializer_1', 'io/activej/serializer/BinaryInput', integer }
    stack: { uninitialized 17, uninitialized 17, integer }
  Bytecode:
    0000000: 2bb6 003a 572b b600 3a57 2bb6 003a 3d1c
    0000010: 57bb 0010 591c c000 16b7 003d 4e2d 572d
    0000020: b0                                     

	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3061)
	at java.base/java.lang.Class.getField0(Class.java:3246)
	at java.base/java.lang.Class.getField(Class.java:1997)
	at io.activej.codegen.ClassBuilder.build(ClassBuilder.java:305)
	at io.activej.codegen.ClassBuilder.buildClassAndCreateNewInstance(ClassBuilder.java:447)
	at io.activej.serializer.SerializerBuilder.buildImpl(SerializerBuilder.java:854)
	at io.activej.serializer.SerializerBuilder.build(SerializerBuilder.java:316)
	at io.activej.serializer.SerializerBuilder.build(SerializerBuilder.java:310)
```

**Comment by eduard-vasinskyi** [comment]
Hello, @gkopff 
To create a new `LocalDate` out of 3 int values (`year`, `month`, `dayOfMonth`) you need to call `LocalDate#of(int, int, int)`.
To describe this in `enoder()` method we can use 
`public static Expression staticCall(Class<?> owner, String method, Expression... arguments)` 
method from [Expressions](https://github.com/activej/activej/blob/master/core-codegen/src/main/java/io/activej/codegen/expression/Expressions.java) class. 

So, just replace this part
```
return sequence(
        readVarInt(in),
        readVarInt(in),
        readVarInt(in));
```

with 
```
return staticCall(LocalDate.class, "of",
	readVarInt(input),
	readVarInt(input),
	readVarInt(input)
);
```


BTW, we have added a standalone [example](https://github.com/activej/activej/blob/master/examples/core/serializer/src/main/java/LocalDateSerializerExample.java) based on this issue. The example illustrates how to write a serializer for `LocalDate` and how to add it to [SerializerBuilder](https://github.com/activej/activej/blob/master/core-serializer/src/main/java/io/activej/serializer/SerializerBuilder.java)

**Comment by gkopff** [comment]
Perfect - thank you. :+1:

One follow-up question:

In `SerializerDef` there is the method: `void accept(Visitor visitor);`.  In `AbstractSerializerDef` it is implemented as an empty method.  Some serializer implementations override that method with an implementation like this (the following is from `SerializerDefList`:

```
	@Override
	public void accept(Visitor visitor) {
		visitor.visit(valueSerializer);
	}
```

Under what circumstances do we need to use this _accept visitor_ method?

**Comment by gkopff** [comment]
Thank you.  

I think your serialiser is a really neat approach - nice job 💯 .
