### ISSUE TITLE
[core-serializer] Class cast exception when a concrete List class is used for a field.

### ISSUE THREAD

**Issue by gkopff** [activej/activej#60]
I get a `ClassCastException` if a serialised field is specified using a concrete `List` implementation type, rather than the `List` interface type.  The following illustrates.

The driver of this test case:

```
  public static void main(String[] args)
  {
    final BinarySerializer<TheContractImpl> serializer =
        SerializerBuilder.create()
            .build(TheContractImpl.class);

    final byte[] array = new byte[16];
    final TheContractImpl contract = new TheContractImpl(ImmutableList.of("foo", "bar", "baz"));

    final int length = serializer.encode(array, 0, contract);
    System.out.println("Wrote: " + length + " bytes");

    final TheContractImpl decoded = serializer.decode(array, 0);
    System.out.println("Finished: " + decoded);
  }

  public static interface TheContract
  {
    public LinkedList<String> list();
  }
```

### A working program

This version works:

```
  public static class TheContractImpl implements TheContract
  {
    @Serialize(order = 0)
    public final List<String> list;

    public TheContractImpl(@Deserialize("list") final List<String> list)       // receive any list implementation
    {
      this.list = new LinkedList<>(list);                                      // copy the elements to a new object
    }

    @Override
    public LinkedList<String> list()
    {
      return (LinkedList<String>) this.list;
    }

    @Override
    public String toString() { return "TheContractImpl{" + "impl=" + this.list.getClass().getName() + ",list=" + this.list + '}'; }
  }
```

Note that the constructor accepts a `List`.  In the constructor, we copy the elements to a newly constructed linked list and assign that linked list to the `list` field.

This works.  The output is:

```
Wrote: 13 bytes
Finished: TheContractImpl{impl=java.util.LinkedList,list=[foo, bar, baz]}
```

### The problematic program

This version fails:

```
  public static class TheContractImpl implements TheContract
  {
    @Serialize(order = 0)
    public final LinkedList<String> list;

    public TheContractImpl(@Deserialize("list") final List<String> list)       // receive any list implementation
    {
      this.list = new LinkedList<>(list);                                      // copy the elements to a new object
    }

    @Override
    public LinkedList<String> list()
    {
      return (LinkedList<String>) this.list;
    }

    @Override
    public String toString() { return "TheContractImpl{" + "impl=" + this.list.getClass().getName() + ",list=" + this.list + '}'; }
  }
```

The only line that changed was from this:

```
    public final List<String> list;
```

to this:

```
    public final LinkedList<String> list;
```

This fails with:

```
Wrote: 13 bytes
Exception in thread "main" java.lang.ClassCastException: class java.util.Arrays$ArrayList cannot be cast to class java.util.LinkedList (java.util.Arrays$ArrayList and java.util.LinkedList are in module java.base of loader 'bootstrap')
	at io.activej.codegen.io.activej.serializer.BinarySerializer_1.decode(Unknown Source)
	at CastBugApp.main(CastBugApp.java:31)
```

Note: I'm using the `LinkedList` in this example just so the test is without dependencies.  My real-life use of a concrete type is using a Guava `ImmutableList`.

**Comment by eduard-vasinskyi** [comment]
Hello, @gkopff 
Thank you. We have fixed casting issues in 4d458132
This fix will be a part of the ActiveJ v4.1 release

**Comment by gkopff** [comment]
Great news @eduard-vasinskyi  - thank you.

**Comment by eduard-vasinskyi** [comment]
@gkopff 
Feel free to reopen this if the issue still persists
