### ISSUE TITLE
[serializer] java.lang.IllegalArgumentException and docs

### ISSUE THREAD

**Issue by alphaqu** [activej/activej#72]
Hey so i have been working a lot recently with the serializer and this is sortof my review.

i love it, but i still have some  suggestions
First of all please expand your docs because most of the time i  needed to look through the source code to know if it has support for a feature or not
Second of all the serializer errors are fine they tell me what and why its throwing an exception, the deserializer however just threw a java.lang.IllegalArgumentException and i have no idea where 
`Caused by: java.lang.IllegalArgumentException
	at io.activej.codegen.io.activej.serializer.BinarySerializer_10.decode_DashBakedModel_V0(Unknown Source) ~[?:?]
	at io.activej.codegen.io.activej.serializer.BinarySerializer_10.decode_HashMap_V0(Unknown Source) ~[?:?]
	at io.activej.codegen.io.activej.serializer.BinarySerializer_10.decode(Unknown Source) ~[?:?]
	at io.activej.serializer.stream.StreamInput.deserialize(StreamInput.java:139) ~[activej-serializer-4.1.1.jar:?]
	at net.quantumfusion.dash.cache.DashModelLoader.load(DashModelLoader.java:128) ~[Dash.main/:?]
	at net.minecraft.client.render.model.BakedModelManager.handler$zcf000$apply(BakedModelManager.java:587) ~[minecraft-1.16.5-projectmapped-net.fabricmc.yarn-1.16.5+build.5-v2.jar:?]
	at net.minecraft.client.render.model.BakedModelManager.apply(BakedModelManager.java) ~[minecraft-1.16.5-projectmapped-net.fabricmc.yarn-1.16.5+build.5-v2.jar:?]
	at net.minecraft.client.render.model.BakedModelManager.apply(BakedModelManager.java:19) ~[minecraft-1.16.5-projectmapped-net.fabricmc.yarn-1.16.5+build.5-v2.jar:?]
	at net.minecraft.resource.SinglePreparationResourceReloadListener.method_18790(SinglePreparationResourceReloadListener.java:13) ~[minecraft-1.16.5-projectmapped-net.fabricmc.yarn-1.16.5+build.5-v2.jar:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_282]
	... 89 more` 
	
The source code is available on [https://github.com/alphaqu/DashLoader](https://github.com/alphaqu/DashLoader ) if you wanna take a look at it but for the last day or so ive  just been stuck not knowing what is causing the error.

**Comment by eduard-vasinskyi** [comment]
Hello, @alphaqu
Thank you for your suggestions! We are planning to refactor both [ActiveJ Codegen](https://codegen.activej.io/) and [ActiveJ Serializer](https://serializer.activej.io/) modules and add more meaningful error messages. If there were some unclear parts in documentation or some features undocumented, please tell us what should be added, we will update the documentation.
 
If you need to debug and look under the hood of a serializer, you can use `SerializerBuilder#withgeneratedBytecodePath` method to pass a directory to which generated class of [BinarySerializer](https://github.com/activej/activej/blob/master/core-serializer/src/main/java/io/activej/serializer/BinarySerializer.java) would be saved. You can then investigate what is going on in the serializer code. Or if you do not want (cannot) modify existing code, you may run the application with `-DSerializerBuilder.saveDir=/path/to/generated/classes` option, which would also save generated classes to that directory.
 
Based on the stack trace of an exception you provided, the `IllegalArgumentException` is thrown when deserializing a `Map`. You have specified Map values to be serialized as one of 4 different `DashBakedModel` implementations. So, the serializer writes a single byte (0-3) to distinguish which implementation to deserialize. Apparently, a byte with a value different than 0-3 was found, leading to `IllegalArgumentException` being thrown.
 
I have noticed that you have mixed up paths when serializing/deserializing `DashBlockStateData.class` and `DashModelData.class`. You serialize state data to the `blockstatePath` file and model to the `modelPath` file. But, when deserializing you use `blockstatePath` both for block state data and model (that is in `DashModelLoader.java` file).
If fixing paths did not resolve `IllegelArgumentException`, please provide a snippet of code (or add a unit test to your repo) that leads to an exception, as I do not have experience in writing Minecraft modes.

**Comment by alphaqu** [comment]
Yes changing paths did resolve the issue, sorry for opening an issue for a non-existent problem.

**Comment by alphaqu** [comment]
On the docs side i think most annotations should be added to the docs
