### ISSUE TITLE
Error http client

### ISSUE THREAD

**Issue by azzahrah** [activej/activej#75]
i don't know what make this wong

```
 String url = "https://mynominatimserver.com/nominatim/reverse.php?format=json&accept-language=id&" + ext;
        SSLContext sslContext = null;
        try {
            sslContext = SSLContext.getDefault();
        } catch (NoSuchAlgorithmException ex) {
            callback.onFinish(false, ex.getMessage());
            return;
        }
        AsyncHttpClient httpClient = AsyncHttpClient
                .create(eventloop)                
                .withSslEnabled(sslContext, eventloop);

        eventloop.submit(() -> {
            httpClient.request(HttpRequest.get(url))
                    .then(HttpMessage::loadBody)
                    .map(body -> body.getString(UTF_8))
                    .whenComplete((String t, Throwable thrwbl) -> {
                        try {
                            JsonObject jo = gson.fromJson(t, JsonObject.class);
                            if (jo.has("display_name")) {
                                callback.onFinish(true, jo.get("display_name").getAsString());
                            } else {
                                callback.onFinish(false, "");
                            }
                        } catch (Exception ex) {
                            callback.onFinish(false, "");
                        }
                    }).whenException(Throwable::printStackTrace);
        });

        eventloop.run();

```

Error
```
java.nio.channels.ClosedSelectorException
        at java.base/sun.nio.ch.SelectorImpl.ensureOpen(SelectorImpl.java:75)
        at java.base/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:118)
        at java.base/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:136)
        at io.activej.eventloop.Eventloop.run(Eventloop.java:401)
        at com.pusatgps.device.DeviceInfo.reverse(DeviceInfo.java:371)
        at com.pusatgps.device.DeviceInfo.doUpdatePosition(DeviceInfo.java:438)
        at com.pusatgps.device.DeviceInfo.lambda$setTerminalInfoAndUpdatePosition$30(DeviceInfo.java:1823)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by eduard-vasinskyi** [comment]
Hello, @azzahrah 
Could you please provide a working snippet that demonstrates the problem? I could not recreate it based on the above code. The server in the example is not found, plus it would be helpful to see how you create and use the Eventloop.

**Comment by azzahrah** [comment]
problem solve by creating dedicated thread for handle eventloop
```
new Thread(()->{
    eventloop.keepalive(true);
    eventloop.run();
}
```
