### ISSUE TITLE
NullPointerException on Void response handle 

### ISSUE THREAD

**Issue by tipame** [activej/activej#77]
Hello, i'm trying to send RPC with Void response type:

`rpcClient.<MyCommand, Void>sendRequest(new MyCommand()).toCompletableFuture().get(1000, TimeUnit.SECONDS);`

on the server side handle request like this:

```
private RpcRequestHandler<MyCommand, Void> createHandler() {
        return myCommand -> Promise.ofCallback(callback -> {
            try {
                // some logic
                callback.set(null); // notify logic done successfully

            } catch (Throwable e) {
                log.error("Exception handling my command", e);
                callback.setException(e);
            }
        });
    }
```

but then client handle response i get:
```
io.activej.common.exception.UnknownFormatException: Parse exception, io.activej.datastream.csp.ChannelDeserializer@2011c0 : bufs:1 bytes:6
	at io.activej.datastream.csp.ChannelDeserializer.onResumed(ChannelDeserializer.java:86)
	at io.activej.datastream.AbstractStreamSupplier.resume(AbstractStreamSupplier.java:144)
	at io.activej.datastream.AbstractStreamSupplier.asyncResume(AbstractStreamSupplier.java:137)
	at io.activej.datastream.csp.ChannelDeserializer.lambda$onResumed$1(ChannelDeserializer.java:115)
	at io.activej.promise.AbstractPromise$7.accept(AbstractPromise.java:419)
	at io.activej.promise.AbstractPromise$CallbackList.accept(AbstractPromise.java:795)
	at io.activej.promise.AbstractPromise.complete$$$capture(AbstractPromise.java:116)
	at io.activej.promise.AbstractPromise.complete(AbstractPromise.java)
	at io.activej.promise.SettablePromise.set$$$capture(SettablePromise.java:68)
	at io.activej.promise.SettablePromise.set(SettablePromise.java)
	at io.activej.csp.queue.ChannelZeroBuffer.put(ChannelZeroBuffer.java:86)
	at io.activej.csp.queue.ChannelQueue$1.doAccept(ChannelQueue.java:66)
	at io.activej.csp.AbstractChannelConsumer.accept(AbstractChannelConsumer.java:52)
	at io.activej.csp.ChannelSuppliers.lambda$streamToImpl$6(ChannelSuppliers.java:226)
	at io.activej.promise.AbstractPromise.complete$$$capture(AbstractPromise.java:116)
	at io.activej.promise.AbstractPromise.complete(AbstractPromise.java)
	at io.activej.promise.SettablePromise.set$$$capture(SettablePromise.java:68)
	at io.activej.promise.SettablePromise.set(SettablePromise.java)
	at io.activej.net.socket.tcp.AsyncTcpSocketNio.onReadReady(AsyncTcpSocketNio.java:385)
	at io.activej.eventloop.Eventloop.onRead(Eventloop.java:804)
	at io.activej.eventloop.Eventloop.optimizedProcessSelectedKeys(Eventloop.java:551)
	at io.activej.eventloop.Eventloop.run(Eventloop.java:413)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at io.activej.rpc.client.RpcClientConnection.accept(RpcClientConnection.java:206)
	at io.activej.rpc.client.RpcClientConnection.accept(RpcClientConnection.java:49)
	at io.activej.datastream.AbstractStreamSupplier.send(AbstractStreamSupplier.java:155)
	at io.activej.datastream.csp.ChannelDeserializer.process(ChannelDeserializer.java:157)
	at io.activej.datastream.csp.ChannelDeserializer.onResumed(ChannelDeserializer.java:81)
	... 22 common frames omitted
```

the reason is line:
`if (message.getData().getClass() == RpcRemoteException.class) `
where data is null...

version:  4.1.1

**Comment by eduard-vasinskyi** [comment]
Hello, @tipame
Right now, there is no support for Void message types. We will add the support in the next release of ActiveJ.

For now, you can use some other class to represent RPC response:

```
public static final VoidResponse VOID_RESPONSE = new VoidResponse();
 
public static class VoidResponse {
}
 
private RpcRequestHandler<MyCommand, VoidResponse> createHandler() {
        return myCommand -> Promise.ofCallback(callback -> {
            try {
                // some logic
                callback.set(VOID_RESPONSE); // notify logic done successfully
 
            } catch (Throwable e) {
                log.error("Exception handling my command", e);
                callback.setException(e);
            }
        });
    }
```
